# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: The Brain Body Dynamics Lab
email: valero@usc.edu
description: > # this means to ignore newlines until "baseurl:"
  The Brain Body Dynamics Laboratory of the University of Southern California. Principal Investigator: Francisco Valero-Cuevas
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://valerolab.org" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
highlighter: pygments